---
title: "Análisis de datos de COVID-19 en Costa Rica - gráficos básicos"
author: "Manuel Vargas"
date: "2022-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Carga de datos
Los análisis presentados en este documento están basados en los datos publicados por el Ministerio de Salud de Costa Rica en [https://geovision.uned.ac.cr/oges/](https://geovision.uned.ac.cr/oges/).

```{r carga-datos}
covid <- read.csv("05_03_22_CSV_GENERAL.csv", sep = ";")
```

Se convierte la variable `FECHA` al tipo `Date`.

```{r conversion-fecha}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")
```

## Opciones generales
Se utiliza notación científica solo si los números tienen más de siete dígitos.

```{r opciones-generales}
options(scipen = 7)
```

## Cantidad de casos a través del tiempo

### Casos positivos

```{r relacion-fecha-positivos}
# Gráfico de líneas
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos positivos de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos positivos"
)

# Formato del eje X
axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)

# Formato del eje Y
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 100000),
  cex.axis = .7
)
```

